# Compose fileのバージョン指定
version: '3'
# どんなコンテナを立ち上げるか
services:
 # laravelを動かすコンテナ
 app:
   # どのポートを開いて繋ぐか。下記はコンテナの80番ポートを開いて、ホストの8000番につなぐ
   ports:
     - "80:80"
   # 先ほど作ったDockerfileを使って、コンテナをビルドするという指定
   build: ./docker/app
   # コンテナの名前を指定
   container_name: job_seeker_laravel_app
   # コンテナとホスト側のディレクトリを同期する場所の指定。laravelのソースが入る予定の場所
   volumes:
    - ./src:/var/www/html
    - ./docker/app/logs:/var/log/apache2
    - ./docker/app/filebeat/filebeat.yml:/etc/filebeat-7.13.3-linux-x86_64/filebeat.yml
   working_dir: /var/www/html/job-seeker-laravel
   command: /bin/bash -c '/etc/init.d/apache2 start && cd /etc/filebeat-7.13.3-linux-x86_64 && ./filebeat -e'
   networks:
     - esnet

   # MySQLを動かすコンテナ
 db:
   # Docker HubからMySQL5.7の公式イメージをダウンロードしてくる指定
   image: mysql:5.7
   container_name: job_seeker_laravel_db
   # コンテナ内の環境変数を指定。環境変数を渡すとビルド時に設定してくれるDockerイメージがあるので、利用の際はDocker Hubのサイトで確認すると良い
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: job_seeker_db
     MYSQL_USER: laravel_user
     MYSQL_PASSWORD: laravel_pass
     TZ: 'Asia/Tokyo'
   # 起動時のコマンド
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   # ディレクトリ同期。設定ファイルとMySQLのデータが保存される場所を同期している。コンテナは基本的に起動時に変更されてもコンテナ自体が止まるとデータが消えてしまうため、保存しておきたいものはホストマシンと同期しておく必要がある。
   volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 3306:3306
   networks:
     - esnet
#ElasticSearchのコンテナ
 elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
   ports:
     - 9200:9200
   environment:
     - discovery.type=single-node
     - node.master=true
     - node.data=true
     - xpack.security.enabled=false
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
   volumes:
     - ./docker/es/esdata:/usr/share/elasticsearch/data
   ulimits:
     memlock:
       soft: -1
       hard: -1
   logging:
     driver: 'json-file'
     options:
       max-size: '10m'
       max-file: '3'
   networks:
     - esnet
   container_name: job_seeker_laravel_es

#kibanaのコンテナ
 kibana:
   image: docker.elastic.co/kibana/kibana:7.5.1
   ports:
     - 5601:5601
   volumes:
     - "./docker/kibana/:/usr/share/kibana/config/"
   environment:
     ELASTICSEARCH_HOSTS: http://elasticsearch:9200
   networks:
     - esnet
   container_name: job_seeker_laravel_kibana

 logstash:
   image: docker.elastic.co/logstash/logstash:7.13.2
   tty: true
   ports:
    - 5044:5044
   volumes:
    - "./docker/logstash/pipeline/:/usr/share/logstash/pipeline/"
   networks:
    - esnet
   container_name: job_seeker_laravel_logstash
   links:
    - elasticsearch:elasticsearch
   depends_on:
    - elasticsearch
    


# Elasticsearchとその他のコンテナを同じdocker network上に起動させるため、networksを作成
networks:
  esnet:


volumes:
  esdata:
    driver: local















